[package]
name = "rsinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
hw-linux = { git = "https://github.com/CodersCreative/hw-linux.git", version = "0.1.0" }
ratatui = "0.29.0"
sysinfo = "0.32.0"
